# Generated by Django 5.0.4 on 2025-05-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app_staff', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
